name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Build
        run: |
          CGO_ENABLED=0 go build -v -ldflags "-w -s -extldflags '-static' -X 'github.com/NekoWheel/NekoBox/internal/conf.BuildCommit=$GITHUB_SHA'" -o NekoBox .
          pwd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: NekoBox
          path: /home/runner/work/NekoBox/NekoBox

      - name: Set env
        run: echo "IMAGE_TAG=$(date -u '+%Y%m%d-%I%M%S')" >> $GITHUB_ENV

      - name: Create Docker tag
        run: |
          echo "::set-output name=tags::latest,$IMAGE_TAG"

      - name: Build & Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          tags: ${{ steps.create_docker_tags.outputs.tags }}
