name: Docker
on:
  push:
    branches:
      - master

jobs:
  build-arm:
    runs-on: raspberrypi
    permissions:
      actions: write
      contents: read
      packages: write
    steps:
      - name: Compute image tag name
        run: echo "IMAGE_TAG=$(echo $GITHUB_REF_NAME)" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          build-args: |
            GITHUB_SHA=${{ github.sha }}
          tags: |
            ghcr.io/nekowheel/nekobox:${{ env.IMAGE_TAG }}
